=== VaighaiselvanGit/Web-Technologies-Programs/Exercise3/newspaperSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
 targetNamespace="http://www.example.org/newspaperSchema"
  xmlns:tns="http://www.example.org/newspaperSchema" 
  elementFormDefault="qualified">
  
  <complexType name="newspaper">
     <sequence>
        <element name="article" type="tns:politics" maxOccurs="3" minOccurs="1"></element>
     </sequence>
     <attribute name="name" type="string" use="required"></attribute>
  </complexType>
  
  <complexType name="politics">
    <sequence>
        <element name="title" type="string"></element>
        <element name="author" type="string"></element>
        <element name="date" type="string"></element>
        <element name="summary" type="string"></element>
    </sequence>
    <attribute name="type" type="string" use="required"></attribute>
  </complexType>
  
  
  <element name="globalnews" type="tns:newspaper"/>
</schema>

=== VaighaiselvanGit/Web-Technologies-Programs/Exercise3/Newnewspaperschema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalnews name="" xmlns:tns="http://www.example.org/newspaperSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.example.org/newspaperSchema newspaperSchema.xsd ">
  <tns:article type="politics">
    <tns:title>GO BACK MODI</tns:title>
    <tns:author>RJB</tns:author>
    <tns:date>1/11/2020</tns:date>
    <tns:summary> Central Government is asking everyone to live with virus
 </tns:summary>
  </tns:article>
  
  <tns:article type="sports">
    <tns:title>WORLD CUP</tns:title>
    <tns:author>RJ</tns:author>
    <tns:date>1/11/2020</tns:date>
    <tns:summary>Next T20 host in INDIA</tns:summary>
  </tns:article>
</tns:globalnews>
